name: Scheduled Upstream Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/runtipi/runtipi-appstore.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout master
          git merge upstream/master --no-edit
          git push origin master
